In [2]:
import os

print(os.getcwd())

e:\Learning\1.AI-DS\Projects\ai-data-analyst-agent\notebooks

In [3]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

In [4]:
from app.loaders.pandas_loader import load_data

In [4]:
df = load_data(
    "uploads/Dataset.csv"
)

df.head()

FileNotFoundError: File not found: uploads\Dataset.csv

In [7]:
#from app.services.data_loader import load_data

df = load_data(
    PROJECT_ROOT / "uploads" / "Dataset.csv"
)

df.head()

  کد پرسنلیجنسیتسنسابقه خدمتتحصیلاتقدوزنحقوقرشته تحصیلیارزیابی عملکرد
0                                x205615869
1                                x213617585
2                                x226717085
3                                x236417887
4                                x246315770

In [12]:
from app.services.data_loader import get_data_info

info = get_data_info(
    df,
    PROJECT_ROOT / "uploads" / "Dataset.csv",
)

print(info)

ModuleNotFoundError: No module named 'app.services.data_loader'

In [9]:
from app.loaders.pandas_loader import load_data

In [13]:
df = load_data(
    PROJECT_ROOT / "uploads" / "Dataset.csv"
)

df.head()

  کد پرسنلیجنسیتسنسابقه خدمتتحصیلاتقدوزنحقوقرشته تحصیلیارزیابی عملکرد
0                                x205615869
1                                x213617585
2                                x226717085
3                                x236417887
4                                x246315770

In [15]:
from app.profiling.profiler import profile_dataset

profile = profile_dataset(df)

profile

{'rows': 31,
 'columns': 1,
 'column_names': ['کد پرسنلی\x1bجنسیت\x1bسن\x1bسابقه خدمت\x1bتحصیلات\x1bقد\x1bوزن\x1bحقوق\x1bرشته تحصیلی\x1bارزیابی عملکرد'],
 'numeric_columns': [],
 'categorical_columns': ['کد پرسنلی\x1bجنسیت\x1bسن\x1bسابقه خدمت\x1bتحصیلات\x1bقد\x1bوزن\x1bحقوق\x1bرشته تحصیلی\x1bارزیابی عملکرد'],
 'missing_values': {'کد پرسنلی\x1bجنسیت\x1bسن\x1bسابقه خدمت\x1bتحصیلات\x1bقد\x1bوزن\x1bحقوق\x1bرشته تحصیلی\x1bارزیابی عملکرد': 0},
 'duplicate_rows': 0}

In [9]:
from pathlib import Path

file_path = Path(
    "../uploads/1b39f246-7723-45b0-aef3-a05a38bef161.csv"
)

with open(
    file_path,
    "rb"
) as f:

    first_line = f.readline()

print(first_line)

b'\xef\xbb\xbf\xda\xa9\xd8\xaf \xd9\xbe\xd8\xb1\xd8\xb3\xd9\x86\xd9\x84\xdb\x8c\x1b\xd8\xac\xd9\x86\xd8\xb3\xdb\x8c\xd8\xaa\x1b\xd8\xb3\xd9\x86\x1b\xd8\xb3\xd8\xa7\xd8\xa8\xd9\x82\xd9\x87 \xd8\xae\xd8\xaf\xd9\x85\xd8\xaa\x1b\xd8\xaa\xd8\xad\xd8\xb5\xdb\x8c\xd9\x84\xd8\xa7\xd8\xaa\x1b\xd9\x82\xd8\xaf\x1b\xd9\x88\xd8\xb2\xd9\x86\x1b\xd8\xad\xd9\x82\xd9\x88\xd9\x82\x1b\xd8\xb1\xd8\xb4\xd8\xaa\xd9\x87 \xd8\xaa\xd8\xad\xd8\xb5\xdb\x8c\xd9\x84\xdb\x8c\x1b\xd8\xa7\xd8\xb1\xd8\xb2\xdb\x8c\xd8\xa7\xd8\xa8\xdb\x8c \xd8\xb9\xd9\x85\xd9\x84\xda\xa9\xd8\xb1\xd8\xaf\r\n'

In [10]:
import pandas as pd

df = pd.read_csv(
    file_path,
    sep="\x1b"
)

df.head()

,کد پرسنلی,جنسیت,سن,سابقه خدمت,تحصیلات,قد,وزن,حقوق,رشته تحصیلی,ارزیابی عملکرد
0,x20,NaN,56,NaN,NaN,158,69,NaN,NaN,NaN
1,x21,NaN,36,NaN,NaN,175,85,NaN,NaN,NaN
2,x22,NaN,67,NaN,NaN,170,85,NaN,NaN,NaN
3,x23,NaN,64,NaN,NaN,178,87,NaN,NaN,NaN
4,x24,NaN,63,NaN,NaN,157,70,NaN,NaN,NaN

In [4]:
print(df.columns.tolist())

['کد پرسنلی', 'جنسیت', 'سن', 'سابقه خدمت', 'تحصیلات', 'قد', 'وزن', 'حقوق', 'رشته تحصیلی', 'ارزیابی عملکرد']

In [11]:
from app.loaders.pandas_loader import load_data
from app.tools.statistics import calculate_statistics


statistics = calculate_statistics(
    df
)

statistics

{'جنسیت': {'count': 0.0,
  'mean': nan,
  'std': nan,
  'min': nan,
  '25%': nan,
  '50%': nan,
  '75%': nan,
  'max': nan},
 'سن': {'count': 31.0,
  'mean': 48.1,
  'std': 14.97,
  'min': 25.0,
  '25%': 35.5,
  '50%': 48.0,
  '75%': 63.5,
  'max': 75.0},
 'سابقه خدمت': {'count': 0.0,
  'mean': nan,
  'std': nan,
  'min': nan,
  '25%': nan,
  '50%': nan,
  '75%': nan,
  'max': nan},
 'تحصیلات': {'count': 0.0,
  'mean': nan,
  'std': nan,
  'min': nan,
  '25%': nan,
  '50%': nan,
  '75%': nan,
  'max': nan},
 'قد': {'count': 31.0,
  'mean': 165.45,
  'std': 10.94,
  'min': 150.0,
  '25%': 156.0,
  '50%': 166.0,
  '75%': 175.5,
  'max': 184.0},
 'وزن': {'count': 31.0,
  'mean': 76.52,
  'std': 7.46,
  'min': 62.0,
  '25%': 70.0,
  '50%': 76.0,
  '75%': 83.5,
  'max': 88.0},
 'حقوق': {'count': 0.0,
  'mean': nan,
  'std': nan,
  'min': nan,
  '25%': nan,
  '50%': nan,
  '75%': nan,
  'max': nan},
 'رشته تحصیلی': {'count': 0.0,
  'mean': nan,
  'std': nan,
  'min': nan,
  '25%': nan,
  '50%': nan,
  '75%': nan,
  'max': nan},
 'ارزیابی عملکرد': {'count': 0.0,
  'mean': nan,
  'std': nan,
  'min': nan,
  '25%': nan,
  '50%': nan,
  '75%': nan,
  'max': nan}}

In [12]:
from app.tools.missing_values import (
    analyze_missing_values
)

missing = analyze_missing_values(
    df
)

missing

{'کد پرسنلی': {'count': 0, 'percentage': 0.0},
 'جنسیت': {'count': 31, 'percentage': 100.0},
 'سن': {'count': 0, 'percentage': 0.0},
 'سابقه خدمت': {'count': 31, 'percentage': 100.0},
 'تحصیلات': {'count': 31, 'percentage': 100.0},
 'قد': {'count': 0, 'percentage': 0.0},
 'وزن': {'count': 0, 'percentage': 0.0},
 'حقوق': {'count': 31, 'percentage': 100.0},
 'رشته تحصیلی': {'count': 31, 'percentage': 100.0},
 'ارزیابی عملکرد': {'count': 31, 'percentage': 100.0}}

In [13]:
from app.tools.correlation import (
    calculate_correlation
)

correlation = calculate_correlation(
    df
)

correlation

{'جنسیت': {'جنسیت': nan,
  'سن': nan,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': nan,
  'وزن': nan,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan},
 'سن': {'جنسیت': nan,
  'سن': 1.0,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': -0.02,
  'وزن': 0.04,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan},
 'سابقه خدمت': {'جنسیت': nan,
  'سن': nan,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': nan,
  'وزن': nan,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan},
 'تحصیلات': {'جنسیت': nan,
  'سن': nan,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': nan,
  'وزن': nan,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan},
 'قد': {'جنسیت': nan,
  'سن': -0.02,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': 1.0,
  'وزن': 0.29,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan},
 'وزن': {'جنسیت': nan,
  'سن': 0.04,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': 0.29,
  'وزن': 1.0,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan},
 'حقوق': {'جنسیت': nan,
  'سن': nan,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': nan,
  'وزن': nan,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan},
 'رشته تحصیلی': {'جنسیت': nan,
  'سن': nan,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': nan,
  'وزن': nan,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan},
 'ارزیابی عملکرد': {'جنسیت': nan,
  'سن': nan,
  'سابقه خدمت': nan,
  'تحصیلات': nan,
  'قد': nan,
  'وزن': nan,
  'حقوق': nan,
  'رشته تحصیلی': nan,
  'ارزیابی عملکرد': nan}}

In [15]:
from app.tools.visualization import (
    create_histogram
)

chart_path = create_histogram(
    df,
    "سن"
)

chart_path

Matplotlib is building the font cache; this may take a moment.

'outputs\\charts\\سن_histogram.png'